package albertoelias.rippll.appsplash.Activities;

import java.io.InputStream;
import java.util.Properties;

import albertoelias.rippll.appsplash.R;
import android.app.Activity;
import android.os.Bundle;
import android.widget.ImageView;
import android.widget.TextView;

// Main activity which is suppose to have buttons to move around the app.
public class HomeActivity extends Activity {

	// Declaring different values thatare in appinfo.properties. These are different for different apps generated by AppSplash.
	private Integer ppid;
	private String splash_image;
	private String app_name;
	
	@Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.home);
        
        // Get the main app image and app name from appinfo.properties
        ImageView homeImage = (ImageView)findViewById(R.id.homeimage);
        loadResources();
        homeImage.setImageResource(R.drawable.home);
        TextView appName = (TextView)findViewById(R.id.appname);
        appName.setText(app_name);
	}
	
	// Method that gets the app information from appinfo.properties and adds them to its respective instance variables. This is an emulation of the .plist file used
	// in the iOS version of AppSplash.
	public void loadResources() {
    	try {
    		// Opens appinfo.properties and loads in an InputStream
    		Properties app_properties = new Properties();
    		InputStream stream = getResources().openRawResource(R.raw.appinfo);
    		app_properties.load(stream);
    		
    		// Adds the information from the InputStream to its respective instance variables.
			ppid = Integer.parseInt((String)app_properties.get("app_ppid"));
    		splash_image = (String)app_properties.get("home_image");
    		app_name = (String)app_properties.get("name");
    		
    	} catch (Exception e) {
    		throw new RuntimeException("Can't load app resources", e);
    	}
    }
}
